model_name: unet_v1
nb_filter: [32, 64, 128, 256, 512]
learning_rate: 0.0001
dataset_img_size: 768
img_size: 384
epochs: 100
batch_size: 16
custom_augmentation: False
source_dataset_path: airbus-ship-detection
destination_dataset_path: datasets/airbus_ship